# .render.yaml
services:
  - type: web
    name: algieri-pizza
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
    envVars:
      - key: DB_HOST
        value: your-db-host-url
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: pizza

